# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/juanpablohernandezmosti/Programming/C++/space-shooters-ecs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/juanpablohernandezmosti/Programming/C++/space-shooters-ecs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/juanpablohernandezmosti/Programming/C++/space-shooters-ecs/CMakeFiles /Users/juanpablohernandezmosti/Programming/C++/space-shooters-ecs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/juanpablohernandezmosti/Programming/C++/space-shooters-ecs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named space-shooters-ecs

# Build rule for target.
space-shooters-ecs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 space-shooters-ecs
.PHONY : space-shooters-ecs

# fast build rule for target.
space-shooters-ecs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/build
.PHONY : space-shooters-ecs/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/main.cpp.s
.PHONY : main.cpp.s

src/App.o: src/App.cpp.o
.PHONY : src/App.o

# target to build an object file
src/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/App.cpp.o
.PHONY : src/App.cpp.o

src/App.i: src/App.cpp.i
.PHONY : src/App.i

# target to preprocess a source file
src/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/App.cpp.i
.PHONY : src/App.cpp.i

src/App.s: src/App.cpp.s
.PHONY : src/App.s

# target to generate assembly for a file
src/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/App.cpp.s
.PHONY : src/App.cpp.s

src/components/ECSEntities/PlayerCharacter.o: src/components/ECSEntities/PlayerCharacter.cpp.o
.PHONY : src/components/ECSEntities/PlayerCharacter.o

# target to build an object file
src/components/ECSEntities/PlayerCharacter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ECSEntities/PlayerCharacter.cpp.o
.PHONY : src/components/ECSEntities/PlayerCharacter.cpp.o

src/components/ECSEntities/PlayerCharacter.i: src/components/ECSEntities/PlayerCharacter.cpp.i
.PHONY : src/components/ECSEntities/PlayerCharacter.i

# target to preprocess a source file
src/components/ECSEntities/PlayerCharacter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ECSEntities/PlayerCharacter.cpp.i
.PHONY : src/components/ECSEntities/PlayerCharacter.cpp.i

src/components/ECSEntities/PlayerCharacter.s: src/components/ECSEntities/PlayerCharacter.cpp.s
.PHONY : src/components/ECSEntities/PlayerCharacter.s

# target to generate assembly for a file
src/components/ECSEntities/PlayerCharacter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ECSEntities/PlayerCharacter.cpp.s
.PHONY : src/components/ECSEntities/PlayerCharacter.cpp.s

src/components/ECSManager.o: src/components/ECSManager.cpp.o
.PHONY : src/components/ECSManager.o

# target to build an object file
src/components/ECSManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ECSManager.cpp.o
.PHONY : src/components/ECSManager.cpp.o

src/components/ECSManager.i: src/components/ECSManager.cpp.i
.PHONY : src/components/ECSManager.i

# target to preprocess a source file
src/components/ECSManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ECSManager.cpp.i
.PHONY : src/components/ECSManager.cpp.i

src/components/ECSManager.s: src/components/ECSManager.cpp.s
.PHONY : src/components/ECSManager.s

# target to generate assembly for a file
src/components/ECSManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ECSManager.cpp.s
.PHONY : src/components/ECSManager.cpp.s

src/components/GameManager.o: src/components/GameManager.cpp.o
.PHONY : src/components/GameManager.o

# target to build an object file
src/components/GameManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/GameManager.cpp.o
.PHONY : src/components/GameManager.cpp.o

src/components/GameManager.i: src/components/GameManager.cpp.i
.PHONY : src/components/GameManager.i

# target to preprocess a source file
src/components/GameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/GameManager.cpp.i
.PHONY : src/components/GameManager.cpp.i

src/components/GameManager.s: src/components/GameManager.cpp.s
.PHONY : src/components/GameManager.s

# target to generate assembly for a file
src/components/GameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/GameManager.cpp.s
.PHONY : src/components/GameManager.cpp.s

src/components/PlayerController.o: src/components/PlayerController.cpp.o
.PHONY : src/components/PlayerController.o

# target to build an object file
src/components/PlayerController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/PlayerController.cpp.o
.PHONY : src/components/PlayerController.cpp.o

src/components/PlayerController.i: src/components/PlayerController.cpp.i
.PHONY : src/components/PlayerController.i

# target to preprocess a source file
src/components/PlayerController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/PlayerController.cpp.i
.PHONY : src/components/PlayerController.cpp.i

src/components/PlayerController.s: src/components/PlayerController.cpp.s
.PHONY : src/components/PlayerController.s

# target to generate assembly for a file
src/components/PlayerController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/PlayerController.cpp.s
.PHONY : src/components/PlayerController.cpp.s

src/components/Window.o: src/components/Window.cpp.o
.PHONY : src/components/Window.o

# target to build an object file
src/components/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/Window.cpp.o
.PHONY : src/components/Window.cpp.o

src/components/Window.i: src/components/Window.cpp.i
.PHONY : src/components/Window.i

# target to preprocess a source file
src/components/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/Window.cpp.i
.PHONY : src/components/Window.cpp.i

src/components/Window.s: src/components/Window.cpp.s
.PHONY : src/components/Window.s

# target to generate assembly for a file
src/components/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/Window.cpp.s
.PHONY : src/components/Window.cpp.s

src/components/WindowBackground.o: src/components/WindowBackground.cpp.o
.PHONY : src/components/WindowBackground.o

# target to build an object file
src/components/WindowBackground.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/WindowBackground.cpp.o
.PHONY : src/components/WindowBackground.cpp.o

src/components/WindowBackground.i: src/components/WindowBackground.cpp.i
.PHONY : src/components/WindowBackground.i

# target to preprocess a source file
src/components/WindowBackground.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/WindowBackground.cpp.i
.PHONY : src/components/WindowBackground.cpp.i

src/components/WindowBackground.s: src/components/WindowBackground.cpp.s
.PHONY : src/components/WindowBackground.s

# target to generate assembly for a file
src/components/WindowBackground.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/WindowBackground.cpp.s
.PHONY : src/components/WindowBackground.cpp.s

src/components/ui/Button.o: src/components/ui/Button.cpp.o
.PHONY : src/components/ui/Button.o

# target to build an object file
src/components/ui/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Button.cpp.o
.PHONY : src/components/ui/Button.cpp.o

src/components/ui/Button.i: src/components/ui/Button.cpp.i
.PHONY : src/components/ui/Button.i

# target to preprocess a source file
src/components/ui/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Button.cpp.i
.PHONY : src/components/ui/Button.cpp.i

src/components/ui/Button.s: src/components/ui/Button.cpp.s
.PHONY : src/components/ui/Button.s

# target to generate assembly for a file
src/components/ui/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Button.cpp.s
.PHONY : src/components/ui/Button.cpp.s

src/components/ui/Canvas.o: src/components/ui/Canvas.cpp.o
.PHONY : src/components/ui/Canvas.o

# target to build an object file
src/components/ui/Canvas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Canvas.cpp.o
.PHONY : src/components/ui/Canvas.cpp.o

src/components/ui/Canvas.i: src/components/ui/Canvas.cpp.i
.PHONY : src/components/ui/Canvas.i

# target to preprocess a source file
src/components/ui/Canvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Canvas.cpp.i
.PHONY : src/components/ui/Canvas.cpp.i

src/components/ui/Canvas.s: src/components/ui/Canvas.cpp.s
.PHONY : src/components/ui/Canvas.s

# target to generate assembly for a file
src/components/ui/Canvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Canvas.cpp.s
.PHONY : src/components/ui/Canvas.cpp.s

src/components/ui/Label.o: src/components/ui/Label.cpp.o
.PHONY : src/components/ui/Label.o

# target to build an object file
src/components/ui/Label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Label.cpp.o
.PHONY : src/components/ui/Label.cpp.o

src/components/ui/Label.i: src/components/ui/Label.cpp.i
.PHONY : src/components/ui/Label.i

# target to preprocess a source file
src/components/ui/Label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Label.cpp.i
.PHONY : src/components/ui/Label.cpp.i

src/components/ui/Label.s: src/components/ui/Label.cpp.s
.PHONY : src/components/ui/Label.s

# target to generate assembly for a file
src/components/ui/Label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Label.cpp.s
.PHONY : src/components/ui/Label.cpp.s

src/components/ui/Sprite.o: src/components/ui/Sprite.cpp.o
.PHONY : src/components/ui/Sprite.o

# target to build an object file
src/components/ui/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Sprite.cpp.o
.PHONY : src/components/ui/Sprite.cpp.o

src/components/ui/Sprite.i: src/components/ui/Sprite.cpp.i
.PHONY : src/components/ui/Sprite.i

# target to preprocess a source file
src/components/ui/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Sprite.cpp.i
.PHONY : src/components/ui/Sprite.cpp.i

src/components/ui/Sprite.s: src/components/ui/Sprite.cpp.s
.PHONY : src/components/ui/Sprite.s

# target to generate assembly for a file
src/components/ui/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Sprite.cpp.s
.PHONY : src/components/ui/Sprite.cpp.s

src/components/ui/Widget.o: src/components/ui/Widget.cpp.o
.PHONY : src/components/ui/Widget.o

# target to build an object file
src/components/ui/Widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Widget.cpp.o
.PHONY : src/components/ui/Widget.cpp.o

src/components/ui/Widget.i: src/components/ui/Widget.cpp.i
.PHONY : src/components/ui/Widget.i

# target to preprocess a source file
src/components/ui/Widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Widget.cpp.i
.PHONY : src/components/ui/Widget.cpp.i

src/components/ui/Widget.s: src/components/ui/Widget.cpp.s
.PHONY : src/components/ui/Widget.s

# target to generate assembly for a file
src/components/ui/Widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/Widget.cpp.s
.PHONY : src/components/ui/Widget.cpp.s

src/components/ui/menus/GameHud.o: src/components/ui/menus/GameHud.cpp.o
.PHONY : src/components/ui/menus/GameHud.o

# target to build an object file
src/components/ui/menus/GameHud.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/menus/GameHud.cpp.o
.PHONY : src/components/ui/menus/GameHud.cpp.o

src/components/ui/menus/GameHud.i: src/components/ui/menus/GameHud.cpp.i
.PHONY : src/components/ui/menus/GameHud.i

# target to preprocess a source file
src/components/ui/menus/GameHud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/menus/GameHud.cpp.i
.PHONY : src/components/ui/menus/GameHud.cpp.i

src/components/ui/menus/GameHud.s: src/components/ui/menus/GameHud.cpp.s
.PHONY : src/components/ui/menus/GameHud.s

# target to generate assembly for a file
src/components/ui/menus/GameHud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/menus/GameHud.cpp.s
.PHONY : src/components/ui/menus/GameHud.cpp.s

src/components/ui/menus/MainMenu.o: src/components/ui/menus/MainMenu.cpp.o
.PHONY : src/components/ui/menus/MainMenu.o

# target to build an object file
src/components/ui/menus/MainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/menus/MainMenu.cpp.o
.PHONY : src/components/ui/menus/MainMenu.cpp.o

src/components/ui/menus/MainMenu.i: src/components/ui/menus/MainMenu.cpp.i
.PHONY : src/components/ui/menus/MainMenu.i

# target to preprocess a source file
src/components/ui/menus/MainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/menus/MainMenu.cpp.i
.PHONY : src/components/ui/menus/MainMenu.cpp.i

src/components/ui/menus/MainMenu.s: src/components/ui/menus/MainMenu.cpp.s
.PHONY : src/components/ui/menus/MainMenu.s

# target to generate assembly for a file
src/components/ui/menus/MainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/components/ui/menus/MainMenu.cpp.s
.PHONY : src/components/ui/menus/MainMenu.cpp.s

src/utils/Timer.o: src/utils/Timer.cpp.o
.PHONY : src/utils/Timer.o

# target to build an object file
src/utils/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/utils/Timer.cpp.o
.PHONY : src/utils/Timer.cpp.o

src/utils/Timer.i: src/utils/Timer.cpp.i
.PHONY : src/utils/Timer.i

# target to preprocess a source file
src/utils/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/utils/Timer.cpp.i
.PHONY : src/utils/Timer.cpp.i

src/utils/Timer.s: src/utils/Timer.cpp.s
.PHONY : src/utils/Timer.s

# target to generate assembly for a file
src/utils/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/space-shooters-ecs.dir/build.make CMakeFiles/space-shooters-ecs.dir/src/utils/Timer.cpp.s
.PHONY : src/utils/Timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... space-shooters-ecs"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/App.o"
	@echo "... src/App.i"
	@echo "... src/App.s"
	@echo "... src/components/ECSEntities/PlayerCharacter.o"
	@echo "... src/components/ECSEntities/PlayerCharacter.i"
	@echo "... src/components/ECSEntities/PlayerCharacter.s"
	@echo "... src/components/ECSManager.o"
	@echo "... src/components/ECSManager.i"
	@echo "... src/components/ECSManager.s"
	@echo "... src/components/GameManager.o"
	@echo "... src/components/GameManager.i"
	@echo "... src/components/GameManager.s"
	@echo "... src/components/PlayerController.o"
	@echo "... src/components/PlayerController.i"
	@echo "... src/components/PlayerController.s"
	@echo "... src/components/Window.o"
	@echo "... src/components/Window.i"
	@echo "... src/components/Window.s"
	@echo "... src/components/WindowBackground.o"
	@echo "... src/components/WindowBackground.i"
	@echo "... src/components/WindowBackground.s"
	@echo "... src/components/ui/Button.o"
	@echo "... src/components/ui/Button.i"
	@echo "... src/components/ui/Button.s"
	@echo "... src/components/ui/Canvas.o"
	@echo "... src/components/ui/Canvas.i"
	@echo "... src/components/ui/Canvas.s"
	@echo "... src/components/ui/Label.o"
	@echo "... src/components/ui/Label.i"
	@echo "... src/components/ui/Label.s"
	@echo "... src/components/ui/Sprite.o"
	@echo "... src/components/ui/Sprite.i"
	@echo "... src/components/ui/Sprite.s"
	@echo "... src/components/ui/Widget.o"
	@echo "... src/components/ui/Widget.i"
	@echo "... src/components/ui/Widget.s"
	@echo "... src/components/ui/menus/GameHud.o"
	@echo "... src/components/ui/menus/GameHud.i"
	@echo "... src/components/ui/menus/GameHud.s"
	@echo "... src/components/ui/menus/MainMenu.o"
	@echo "... src/components/ui/menus/MainMenu.i"
	@echo "... src/components/ui/menus/MainMenu.s"
	@echo "... src/utils/Timer.o"
	@echo "... src/utils/Timer.i"
	@echo "... src/utils/Timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

